# Generated by Django 4.0.1 on 2022-01-19 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_flights', to='flights.city')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flights', to='flights.city')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('EC', 'Economy'), ('BU', 'Business'), ('DE', 'Deluxe')], max_length=2)),
                ('tickets_total', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ranks', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passenger')),
                ('ticket_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.ticketrank')),
            ],
        ),
    ]
