# Generated by Django 4.0.1 on 2022-01-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketrank',
            unique_together={('rank', 'flight')},
        ),
    ]
