# Generated by Django 4.0.1 on 2022-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_ticketrank_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='booking_closed',
            field=models.BooleanField(default=False),
        ),
    ]
